# Generated by Django 3.2 on 2021-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_todo_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='gender',
            field=models.CharField(default='SOME STRING', max_length=6),
        ),
    ]
