# Generated by Django 3.2 on 2021-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_todo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
