# Generated by Django 3.2 on 2021-12-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0004_alter_todo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='gender',
            field=models.CharField(default='male', max_length=6),
        ),
    ]
