# Generated by Django 3.2 on 2021-12-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0005_alter_todo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='year_in_school',
        ),
    ]
