# Generated by Django 3.2 on 2021-12-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0007_auto_20211219_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ambient',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ergonomic',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='individual',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='infrastructure',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='learningactivity',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='learningmode',
            field=models.CharField(default='formal', max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='people',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='rules',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='spatial',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='todo',
            name='virtual',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
